# Generated by Django 3.2.2 on 2021-05-14 11:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=api.models.generate_unique_uid, max_length=30, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(default='customer', max_length=50)),
                ('username', models.CharField(default='user', max_length=50)),
                ('email', models.CharField(default='email', max_length=50, unique=True)),
                ('password', models.CharField(default='12345678', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
